name: Task spoken_digit

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
#        python-version: [3.7, 3.8]
#        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: apt-get
      run: |
        sudo apt-get install -y libsndfile1-dev
    - name: python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/neuralaudio/hear-baseline.git
        pip install -e "."
    - name: wget
      run: |
        wget https://github.com/neuralaudio/hear2021-open-tasks-downsampled/raw/main/preprocessed/hear-2021.0.6-spoken_digit-1.0.9-small-44100.tar.gz
        tar zxvf hear-2021.0.6-spoken_digit-1.0.9-small-44100.tar.gz
    - name: Downstream
      run: |
        python -m heareval.embeddings.runner hearbaseline --tasks-dir hear-2021.0.6/tasks/
        python -m heareval.predictions.runner embeddings/hearbaseline/spoken_digit-1.0.9-small/ --grid faster --grid-points 1